/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

bool_t
xdr_duration (XDR *xdrs, duration *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->seconds))
		 return FALSE;
	return TRUE;
}
