/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
sleep_prog_1(char *host, int x)
{
	CLIENT *clnt;
	void  *result_1;
	duration  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SLEEP_PROG, SLEEP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1_arg.seconds=x;

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sleep_prog_1 (host, atoi(argv[2]));
exit (0);
}
